# OpenWebPanel -- juwel.collage.edu.pl
server {
    listen 80;
    listen [::]:80;
    server_name juwel.collage.edu.pl www.juwel.collage.edu.pl;
    root /home/ubuntu/open-web-panel/homes/password/juwel.collage.edu.pl;
    index index.html index.htm index.php;

    access_log ./nginx/logs/juwel.collage.edu.pl.access.log;
    error_log ./nginx/logs/juwel.collage.edu.pl.error.log;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # ACME HTTP-01 challenge (Let's Encrypt)
    location ^~ /.well-known/acme-challenge/ {
        proxy_pass http://127.0.0.1:9000;
        proxy_set_header Host $host;
    }

    location ~ /\. {
        deny all;
    }

    location ~ /\.owp {
        deny all;
    }
}
